theme: jekyll-theme-dinky
remote_theme: pages-themes/dinky@v0.2.0

title: Human Capital in the Nordic Countries
description: Repository for the HCNC project

show_downloads: false

permalink: /:slug

collections:
  articles:
    output: true
    layout: default
    permalink: /articles/:name
  sources:
    output: true
    layout: default
    permalink: /sources/:name

team:
  - surname: "Ford"
    firstname: "Nick"
    position: "PhD student"
    institution: "Lund University"
    role: ""
    website: "https://www.nickford.com"
    twitter: "nickford"
    github: "nickforddk"
  - surname: "Sharp"
    firstname: "Paul"
    position: "Professor"
    institution: "University of Southern Denmark"
    role: "PI"
    website: "http://www.keynes.dk"
    twitter: "paulsharpechist"
    github: ""
  - surname: "Ranestad"
    firstname: "Kristin"
    position: "Associate Professor"
    institution: "University of Oslo, Lund University"
    role: ""
    website: ""
    twitter: "KristinRanestad"
    github: ""
  - surname: "Dahl"
    firstname: "Christian Møller"
    position: "Professor"
    institution: "University of Southern Denmark"
    role: ""
    website: ""
    twitter: "ChristianMDahl1"
    github: ""
  - surname: "Westermann"
    firstname: "Christian Emil"
    position: "PhD student"
    institution: "University of Southern Denmark"
    role: ""
    website: ""
    twitter: "chrisewester"
    github: "cewestermann"
  - surname: "Sommerseth"
    firstname: "Hilde Leikny"
    position: "Professor"
    institution: "University of Tromsø - The Arctic University of Norway"
    role: "Norwegian Historical Data Centre"
    website: ""
    twitter: "hildeleikny"
    github: ""
  - surname: "Pedersen"
    firstname: "Bjørn-Richard"
    username: "pedersen_br"
    position: "Engineer"
    institution: "University of Tromsø - The Arctic University of Norway"
    role: ""
    website: ""
    twitter: ""
    github: ""
  - surname: "Andersen"
    firstname: "Trygve"
    position: "Engineer"
    institution: "University of Tromsø - The Arctic University of Norway"
    role: ""
    website: ""
    twitter: ""
    github: ""
  - surname: "Boberg-Fazlic"
    firstname: "Nina"
    username: "boberg"
    position: "Junior Professor"
    institution: "TU Dortmund University"
    role: ""
    website: ""
    twitter: ""
    github: ""
  - surname: "Görges"
    firstname: "Tom"
    position: "PhD student"
    institution: "TU Dortmund University"
    role: ""
    website: ""
    twitter: ""
    github: ""
  - surname: "Clark"
    firstname: "Gregory"
    position: "Professor"
    institution: "University of Southern Denmark"
    role: ""
    website: ""
    twitter: ""
    github: ""  
  - surname: "Vedel"
    firstname: "Christian"
    position: "Assistant Professor"
    institution: "University of Southern Denmark"
    role: ""
    website: ""
    twitter: ""
    github: "christianvedels"
  - surname: "Pedersen"
    firstname: "Maja Uhre"
    username: "pedersen_mu"
    position: "Assistant Professor"
    institution: "University of Southern Denmark"
    role: ""
    website: ""
    twitter: ""
    github: ""
  - surname: "Hørlyk Kristensen"
    firstname: " Martin"
    position: "PhD student"
    institution: "University of Southern Denmark"
    role: ""
    website: ""
    twitter: ""
    github: ""
  - surname: "Curtis"
    firstname: "Matthew"
    position: "Assistant Professor"
    institution: "University of Southern Denmark"
    role: ""
    website: ""
    twitter: ""
    github: ""  
  - surname: "Grapengeter"
    firstname: "Maret"
    position: "Research assistant"
    institution: "University of Oslo"
    role: ""
    website: ""
    twitter: ""
    github: ""  
  - surname: "Lien"
    firstname: "Trond"
    position: "Research assistant"
    institution: "University of Oslo"
    role: ""
    website: ""
    twitter: ""
    github: ""  
  - surname: "Nielsen"
    firstname: "Christian"
    position: "Research assistant"
    institution: "University of Southern Denmark"
    role: ""
    website: ""
    twitter: ""
    github: "" 



ignore:
  - surname: ""
    firstname: ""
    position: ""
    institution: ""
    role: ""
    website: ""
    twitter: ""
    github: ""

